CREATE DATABASE deck_db;

CREATE TABLE users(
  id INT AUTO_INCREMENT NOT NULL,
  user VARCHAR(45) NOT NULL,
  email VARCHAR(45) NOT NULL,
  username VARCHAR(45) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE workouts(
  id INT AUTO_INCREMENT NOT NULL,
  workout VARCHAR(45) NOT NULL,
  PRIMARY KEY (id)
);


